# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tak.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tak.proto',
  package='tak',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ttak.proto\x12\x03tak\"%\n\rGameParameter\x12\x14\n\x0c\x62oard_length\x18\x01 \x01(\r\",\n\x0bPlaceAction\x12\x1d\n\x05piece\x18\x01 \x01(\x0e\x32\x0e.tak.PieceType\">\n\nMoveAction\x12!\n\tdirection\x18\x01 \x01(\x0e\x32\x0e.tak.Direction\x12\r\n\x05\x64rops\x18\x02 \x03(\r\"n\n\x08GameTurn\x12\t\n\x01x\x18\x01 \x01(\r\x12\t\n\x01y\x18\x02 \x01(\r\x12!\n\x05place\x18\x03 \x01(\x0b\x32\x10.tak.PlaceActionH\x00\x12\x1f\n\x04move\x18\x04 \x01(\x0b\x32\x0f.tak.MoveActionH\x00\x42\x08\n\x06\x41\x63tion\"B\n\x05Piece\x12\x1c\n\x04type\x18\x01 \x01(\x0e\x32\x0e.tak.PieceType\x12\x1b\n\x13second_player_owned\x18\x02 \x01(\x08\"\"\n\x04Pile\x12\x1a\n\x06pieces\x18\x01 \x03(\x0b\x32\n.tak.Piece\"r\n\tGameState\x12\x14\n\x0c\x62oard_length\x18\x01 \x01(\r\x12\x18\n\x10remaining_stones\x18\x02 \x03(\r\x12\x1b\n\x13remaining_capstones\x18\x03 \x03(\r\x12\x18\n\x05\x62oard\x18\x04 \x03(\x0b\x32\t.tak.Pile*5\n\tDirection\x12\t\n\x05NORTH\x10\x00\x12\x08\n\x04\x45\x41ST\x10\x01\x12\t\n\x05SOUTH\x10\x02\x12\x08\n\x04WEST\x10\x03*=\n\tPieceType\x12\x0e\n\nFLAT_STONE\x10\x00\x12\x12\n\x0eSTANDING_STONE\x10\x01\x12\x0c\n\x08\x43\x41PSTONE\x10\x02\x62\x06proto3'
)

_DIRECTION = _descriptor.EnumDescriptor(
  name='Direction',
  full_name='tak.Direction',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NORTH', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EAST', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SOUTH', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WEST', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=499,
  serialized_end=552,
)
_sym_db.RegisterEnumDescriptor(_DIRECTION)

Direction = enum_type_wrapper.EnumTypeWrapper(_DIRECTION)
_PIECETYPE = _descriptor.EnumDescriptor(
  name='PieceType',
  full_name='tak.PieceType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FLAT_STONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STANDING_STONE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CAPSTONE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=554,
  serialized_end=615,
)
_sym_db.RegisterEnumDescriptor(_PIECETYPE)

PieceType = enum_type_wrapper.EnumTypeWrapper(_PIECETYPE)
NORTH = 0
EAST = 1
SOUTH = 2
WEST = 3
FLAT_STONE = 0
STANDING_STONE = 1
CAPSTONE = 2



_GAMEPARAMETER = _descriptor.Descriptor(
  name='GameParameter',
  full_name='tak.GameParameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='board_length', full_name='tak.GameParameter.board_length', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=55,
)


_PLACEACTION = _descriptor.Descriptor(
  name='PlaceAction',
  full_name='tak.PlaceAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='piece', full_name='tak.PlaceAction.piece', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=101,
)


_MOVEACTION = _descriptor.Descriptor(
  name='MoveAction',
  full_name='tak.MoveAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='direction', full_name='tak.MoveAction.direction', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='drops', full_name='tak.MoveAction.drops', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=165,
)


_GAMETURN = _descriptor.Descriptor(
  name='GameTurn',
  full_name='tak.GameTurn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='tak.GameTurn.x', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='tak.GameTurn.y', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='place', full_name='tak.GameTurn.place', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='move', full_name='tak.GameTurn.move', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Action', full_name='tak.GameTurn.Action',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=167,
  serialized_end=277,
)


_PIECE = _descriptor.Descriptor(
  name='Piece',
  full_name='tak.Piece',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='tak.Piece.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='second_player_owned', full_name='tak.Piece.second_player_owned', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=345,
)


_PILE = _descriptor.Descriptor(
  name='Pile',
  full_name='tak.Pile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pieces', full_name='tak.Pile.pieces', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=347,
  serialized_end=381,
)


_GAMESTATE = _descriptor.Descriptor(
  name='GameState',
  full_name='tak.GameState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='board_length', full_name='tak.GameState.board_length', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='remaining_stones', full_name='tak.GameState.remaining_stones', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='remaining_capstones', full_name='tak.GameState.remaining_capstones', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='board', full_name='tak.GameState.board', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=383,
  serialized_end=497,
)

_PLACEACTION.fields_by_name['piece'].enum_type = _PIECETYPE
_MOVEACTION.fields_by_name['direction'].enum_type = _DIRECTION
_GAMETURN.fields_by_name['place'].message_type = _PLACEACTION
_GAMETURN.fields_by_name['move'].message_type = _MOVEACTION
_GAMETURN.oneofs_by_name['Action'].fields.append(
  _GAMETURN.fields_by_name['place'])
_GAMETURN.fields_by_name['place'].containing_oneof = _GAMETURN.oneofs_by_name['Action']
_GAMETURN.oneofs_by_name['Action'].fields.append(
  _GAMETURN.fields_by_name['move'])
_GAMETURN.fields_by_name['move'].containing_oneof = _GAMETURN.oneofs_by_name['Action']
_PIECE.fields_by_name['type'].enum_type = _PIECETYPE
_PILE.fields_by_name['pieces'].message_type = _PIECE
_GAMESTATE.fields_by_name['board'].message_type = _PILE
DESCRIPTOR.message_types_by_name['GameParameter'] = _GAMEPARAMETER
DESCRIPTOR.message_types_by_name['PlaceAction'] = _PLACEACTION
DESCRIPTOR.message_types_by_name['MoveAction'] = _MOVEACTION
DESCRIPTOR.message_types_by_name['GameTurn'] = _GAMETURN
DESCRIPTOR.message_types_by_name['Piece'] = _PIECE
DESCRIPTOR.message_types_by_name['Pile'] = _PILE
DESCRIPTOR.message_types_by_name['GameState'] = _GAMESTATE
DESCRIPTOR.enum_types_by_name['Direction'] = _DIRECTION
DESCRIPTOR.enum_types_by_name['PieceType'] = _PIECETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GameParameter = _reflection.GeneratedProtocolMessageType('GameParameter', (_message.Message,), {
  'DESCRIPTOR' : _GAMEPARAMETER,
  '__module__' : 'tak_pb2'
  # @@protoc_insertion_point(class_scope:tak.GameParameter)
  })
_sym_db.RegisterMessage(GameParameter)

PlaceAction = _reflection.GeneratedProtocolMessageType('PlaceAction', (_message.Message,), {
  'DESCRIPTOR' : _PLACEACTION,
  '__module__' : 'tak_pb2'
  # @@protoc_insertion_point(class_scope:tak.PlaceAction)
  })
_sym_db.RegisterMessage(PlaceAction)

MoveAction = _reflection.GeneratedProtocolMessageType('MoveAction', (_message.Message,), {
  'DESCRIPTOR' : _MOVEACTION,
  '__module__' : 'tak_pb2'
  # @@protoc_insertion_point(class_scope:tak.MoveAction)
  })
_sym_db.RegisterMessage(MoveAction)

GameTurn = _reflection.GeneratedProtocolMessageType('GameTurn', (_message.Message,), {
  'DESCRIPTOR' : _GAMETURN,
  '__module__' : 'tak_pb2'
  # @@protoc_insertion_point(class_scope:tak.GameTurn)
  })
_sym_db.RegisterMessage(GameTurn)

Piece = _reflection.GeneratedProtocolMessageType('Piece', (_message.Message,), {
  'DESCRIPTOR' : _PIECE,
  '__module__' : 'tak_pb2'
  # @@protoc_insertion_point(class_scope:tak.Piece)
  })
_sym_db.RegisterMessage(Piece)

Pile = _reflection.GeneratedProtocolMessageType('Pile', (_message.Message,), {
  'DESCRIPTOR' : _PILE,
  '__module__' : 'tak_pb2'
  # @@protoc_insertion_point(class_scope:tak.Pile)
  })
_sym_db.RegisterMessage(Pile)

GameState = _reflection.GeneratedProtocolMessageType('GameState', (_message.Message,), {
  'DESCRIPTOR' : _GAMESTATE,
  '__module__' : 'tak_pb2'
  # @@protoc_insertion_point(class_scope:tak.GameState)
  })
_sym_db.RegisterMessage(GameState)


# @@protoc_insertion_point(module_scope)
